### PR TITLE
Add environment resource admin pages 3Blades/react-frontend#83

### PR DESCRIPTION
**Pull request by jkp85**
Signed-off-by: Jan Kowalski <jankowalskipraca85@gmail.com>

### CODE REVIEW

**Comment by jgwerner** [comment]
@jkp85 what issue should this PR be tied into?

**Comment by jkp85** [comment]
https://github.com/3Blades/react-frontend/issues/83

**Comment by jkp85** [comment]
Url for managing environment resources will be `/tbs-admin/servers/environmentresource/`

**Comment by jgwerner** [comment]
@jkp85 @johngriebel how about we merge this PR and rebase file handler PR?

**Comment by jkp85** [comment]
Fine by me

**Pull request merged**
