### PR TITLE
Revert "Revert "fix relative import bug in loading""

### PR DESCRIPTION
**Pull request by jgwerner**
Reverts 3Blades/app-backend#19

### CODE REVIEW

**Comment by jgwerner** [comment]
Done.

**Comment by rmorshea** [comment]
Haha, oh man you reverted my commit to revert it.

**Comment by jgwerner** [comment]
From scratch!

**Comment by rmorshea** [comment]
Can we revert this one then? The bug fix was really only a couple lines, and I accidentally added more files than intended.

**Comment by jgwerner** [comment]
Sure thing.

**Pull request merged**
