### PR TITLE
make Model a test util

### PR DESCRIPTION
**Pull request by rmorshea**
I couldn't find any uses for `servers.models.Model` outside of test cases.

Close this if that is not the case.

### CODE REVIEW

**Comment by jkp85** [comment]
@rmorshea this is crucial part of our architecture and can't be removed.

**Comment by rmorshea** [comment]
@jkp85 I couldn't find any uses of this model on `master`. Do you explicitly use the table name somewhere in the codebase?

**Comment by jkp85** [comment]
@rmorshea You won't find this called explicitly. It's used to run user model container.

**Comment by rmorshea** [comment]
@jkp85 why are you using `Model` instead of `Job`?

**Pull request closed without merging**
