### PR TITLE
Remove namespace from user endpoints

### PR DESCRIPTION
**Pull request by johngriebel**
feature/issue #158 - Remove the namespace parameter, add some unit tests.

### CODE REVIEW

**Comment by johngriebel** [comment]
This is not ready to merge. I've found some issues that earlier testing did not expose.

**Comment by johngriebel** [comment]
@jgwerner The latest commit will require some additional changes to the documentation. Specifically, `/users/` is now routed to `users/profiles` and `/users/emails/{address}` is now routed to `/users/emails/{id}/` where `id` is now a UUID. I can (and will) make the documentation changes, but what should the version be? 1.2.1?

**Comment by jkp85** [comment]
@johngriebel Wy did you add `id` field to email model?

**Comment by johngriebel** [comment]
@jkp85 I don't see any compelling reasons to use `address` as a primary key, especially given the added complexity for clients creating requests with special characters (@) in them. Adding an id field also creates consistency with the rest of our API.

**Comment by johngriebel** [comment]
Granted that complexity isn't a huge deal, and is something clients will have to do anyhow if they want to filter on address. Aside from that though, Email won't be a very high traffic table so the performance hit of maintaining an additional uniqueness constraint/index doesn't outweigh the clarity gained with the `id` column.

**Comment by jgwerner** [comment]
@johngriebel @jkp85 ok, I'll bump SwaggerHub project version and update doc with the above. I'll roll this change into an epic which considers other documentation changes.

**Pull request merged**
