### PR TITLE
Feature/search

### PR DESCRIPTION
**Pull request by jkp85**
Implements user search. 3Blades/3blades#42

### CODE REVIEW

**Comment by raygesualdo** [comment]
@jgwerner @jkp85 An idea: should we not localize search to users, but instead create a `/{namespace}/search` endpoint that we can pass query param or POST data to in order to filter on what results we want returned? That way we can have one URL for searching users, projects, servers, etc. We can specify what type of values we want searched (users vs projects, etc.) as a part of the request.

**Comment by jkp85** [comment]
@raygesualdo Yes, this is possible.

**Comment by raygesualdo** [comment]
That's good to know. The question now is what *should* the search behavior be.

**Comment by jkp85** [comment]
Right. In my opinion one global endpoint makes more sense. You could search similar to github where one search query returns code, issues and commits.

**Comment by raygesualdo** [comment]
Agreed.

**Comment by jgwerner** [comment]
@jkp85 @raygesualdo i agree with having one endpoint for search. It creates simpler API docs, too.

**Comment by jkp85** [comment]
Ok then. I will close this PR and implement general search.

**Pull request closed without merging**
